"""
schema.py — generated by scripts/codegen-python-schema.ts.

Do NOT edit by hand. Run `npx tsx scripts/codegen-python-schema.ts` after
changing the Zod schemas in packages/cu-core/src/types.ts.

Source of truth: @rachael/cu-core Action / Observation / Locator schemas.
"""

from __future__ import annotations

from typing import Any, Dict, Iterable

ACTION_VERBS = ["Click","Type","Key","Hint","Scroll","Wait","Goto","Shell","Composite"]
LOCATOR_KINDS = ["selector","uia","hint","mark","coords"]
OBSERVATION_KINDS = ["AxTree","DomSnapshot","UiaTree","SomScreenshot","RawScreenshot","TextDump"]

_REQUIRED_BY_VERB: Dict[str, list] = {
    "Click": [
        "target"
    ],
    "Type": [
        "text"
    ],
    "Key": [
        "chord"
    ],
    "Hint": [
        "hint"
    ],
    "Scroll": [],
    "Wait": [],
    "Goto": [
        "url"
    ],
    "Shell": [
        "cmd"
    ],
    "Composite": [
        "steps"
    ]
}
_REQUIRED_BY_LOCATOR: Dict[str, list] = {
    "selector": [
        "css"
    ],
    "uia": [],
    "hint": [
        "key"
    ],
    "mark": [
        "mark"
    ],
    "coords": [
        "x",
        "y"
    ]
}


def _require(d: Dict[str, Any], keys: Iterable[str]) -> None:
    for k in keys:
        if k not in d:
            raise ValueError(f"missing required field: {k}")


def validate_locator(loc: Dict[str, Any]) -> Dict[str, Any]:
    if not isinstance(loc, dict):
        raise ValueError("locator must be a dict")
    kind = loc.get("kind")
    if kind not in LOCATOR_KINDS:
        raise ValueError(f"unknown locator kind: {kind!r}")
    _require(loc, _REQUIRED_BY_LOCATOR.get(kind, []))
    if kind == "uia" and not any(loc.get(k) for k in ("automationId", "controlType", "name", "path")):
        raise ValueError("uia locator requires at least one of automationId/controlType/name/path")
    return loc


def validate_action(action: Dict[str, Any]) -> Dict[str, Any]:
    if not isinstance(action, dict):
        raise ValueError("action must be a dict")
    verb = action.get("verb")
    if verb not in ACTION_VERBS:
        raise ValueError(f"unknown verb: {verb!r}")
    _require(action, _REQUIRED_BY_VERB.get(verb, []))

    if verb in ("Click", "Type", "Scroll") and action.get("target") is not None:
        validate_locator(action["target"])
    if verb == "Wait" and action.get("ms") is None and action.get("until") is None:
        raise ValueError("Wait requires either ms or until")
    if verb == "Composite":
        if not isinstance(action.get("steps"), list):
            raise ValueError("Composite.steps must be a list")
        for step in action["steps"]:
            validate_action(step)
    return action


def validate_observation(obs: Dict[str, Any]) -> Dict[str, Any]:
    if not isinstance(obs, dict):
        raise ValueError("observation must be a dict")
    _require(obs, ["kind", "surfaceId", "timestamp", "digest"])
    kind = obs["kind"]
    if kind not in OBSERVATION_KINDS:
        raise ValueError(f"unknown observation kind: {kind!r}")
    if kind == "UiaTree" and not isinstance(obs.get("elements"), list):
        raise ValueError("UiaTree observation requires elements list")
    if kind in ("RawScreenshot", "SomScreenshot"):
        _require(obs, ["imageRef"])
    if kind == "TextDump":
        _require(obs, ["text"])
    return obs
