const NL = String.fromCharCode(10);

export function generateBriefingHtml(briefingText: string, title: string, dateStamp: string, tag: string): string {
  const escaped = briefingText.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
  const sectionSplitRe = new RegExp(NL + "(?=## )");
  const sections = escaped.split(sectionSplitRe);
  let body = "";
  for (const section of sections) {
    const headerMatch = section.match(/^## (.+)/);
    if (headerMatch) {
      const sTitle = headerMatch[1];
      const content = section.substring(headerMatch[0].length).trim();
      const sectionId = sTitle.replace(/[^a-zA-Z0-9]/g, "-").toLowerCase();
      body += '<details open id="' + sectionId + '"><summary>' + sTitle + "</summary><div class=\"section-content\">" + NL;
      const lines = content.split(NL);
      for (const line of lines) {
        const urlRe = /(https?:\/\/[^\s)]+)/g;
        const linked = line.replace(urlRe, '<a href="$1" target="_blank">$1</a>');
        if (line.startsWith("- ") || line.startsWith("* ")) body += "<li>" + linked.substring(2) + "</li>" + NL;
        else if (line.startsWith("### ")) body += "<h3>" + line.substring(4) + "</h3>" + NL;
        else if (line.trim()) body += "<p>" + linked + "</p>" + NL;
      }
      body += "</div></details>" + NL;
    } else if (section.trim()) {
      body += "<p>" + section.replace(new RegExp(NL, "g"), "<br>") + "</p>" + NL;
    }
  }
  return '<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">' +
    "<title>" + title + " - " + dateStamp + "</title>" +
    '<link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;600&display=swap" rel="stylesheet">' +
    "<style>" +
    "*{box-sizing:border-box}body{font-family:'IBM Plex Mono',monospace;background:#0a0a0f;color:#b8c4b8;margin:0;padding:20px;line-height:1.6}" +
    "h1{color:#00ff41;border-bottom:1px solid #00ff41;padding-bottom:8px;font-size:1.4em;text-shadow:0 0 10px rgba(0,255,65,0.3)}" +
    "h2,summary{color:#00ff41;font-size:1.1em;cursor:pointer;padding:8px 0}" +
    "h3{color:#4fc3f7;font-size:1em;margin:12px 0 4px}" +
    "details{border:1px solid #1a3a1a;border-radius:4px;margin:12px 0;padding:8px 16px;background:#0d1117}" +
    "details[open] summary{border-bottom:1px solid #1a3a1a;margin-bottom:8px}" +
    "summary:hover{text-shadow:0 0 8px rgba(0,255,65,0.5)}" +
    "a{color:#4fc3f7;text-decoration:none}a:hover{text-decoration:underline;text-shadow:0 0 5px rgba(79,195,247,0.3)}" +
    "li{margin:4px 0;list-style-type:none}li::before{content:'> ';color:#00ff41}" +
    "p{margin:6px 0}" +
    ".meta{color:#666;font-size:0.85em;border-top:1px solid #1a3a1a;padding-top:8px;margin-top:24px}" +
    "@media(max-width:600px){body{padding:10px}details{padding:6px 10px}}" +
    "</style></head><body>" +
    "<h1>[rachael] " + title + "</h1>" +
    "<p style=\"color:#666;font-size:0.85em\">" + dateStamp + " | Rachael Autonomous Agent System</p>" +
    body +
    '<div class="meta">Generated by ' + tag + ' | Rachael</div>' +
    "</body></html>";
}

export async function saveBriefingHtml(html: string, filename: string): Promise<string> {
  const fs = await import("fs");
  const pathMod = await import("path");
  const briefingsDir = pathMod.join(process.cwd(), ".briefings");
  if (!fs.existsSync(briefingsDir)) fs.mkdirSync(briefingsDir, { recursive: true });
  const dest = pathMod.join(briefingsDir, filename);
  fs.writeFileSync(dest, html);
  const domain = (process.env.REPLIT_DOMAINS || "").split(",")[0].trim();
  const baseUrl = domain ? "https://" + domain : "http://localhost:5000";
  return baseUrl + "/briefings/" + filename;
}

export async function pushViaNtfy(
  briefingText: string,
  htmlUrl: string,
  title: string,
  tags: string,
  baseApiUrl: string,
  headers: Record<string, string>,
): Promise<string> {
  let notifyChannel = "";
  let notifyEmail = "";
  try { const r = await fetch(baseApiUrl + "/api/config/notify_channel", { headers }); if (r.ok) { const d = await r.json(); notifyChannel = d.value || ""; } } catch {}
  try { const r = await fetch(baseApiUrl + "/api/config/notify_email", { headers }); if (r.ok) { const d = await r.json(); notifyEmail = d.value || ""; } } catch {}

  if (!notifyChannel) return "no notify_channel configured";

  const plainText = briefingText.slice(0, 3900);
  const ntfyHeaders: Record<string, string> = {
    "Title": title,
    "Priority": "default",
    "Tags": tags,
  };
  if (htmlUrl) {
    ntfyHeaders["Click"] = htmlUrl;
    ntfyHeaders["Actions"] = "view, Read Full Brief, " + htmlUrl;
  }
  if (notifyEmail) ntfyHeaders["Email"] = notifyEmail;

  try {
    const resp = await fetch("https://ntfy.sh/" + notifyChannel, {
      method: "POST",
      headers: ntfyHeaders,
      body: plainText,
      signal: AbortSignal.timeout(15000),
    });
    return resp.ok ? "sent to " + notifyChannel : "ntfy error: " + resp.status;
  } catch (e: any) {
    return "notify error: " + (e.message || "").slice(0, 80);
  }
}

export async function saveBriefingAndNotify(
  briefingText: string,
  filename: string,
  title: string,
  htmlTitle: string,
  dateStamp: string,
  tag: string,
  ntfyTags: string,
  baseApiUrl: string,
  headers: Record<string, string>,
): Promise<{ htmlUrl: string; notifyStatus: string }> {
  const html = generateBriefingHtml(briefingText, htmlTitle, dateStamp, tag);
  const htmlUrl = await saveBriefingHtml(html, filename);
  const notifyStatus = await pushViaNtfy(briefingText, htmlUrl, title, ntfyTags, baseApiUrl, headers);
  return { htmlUrl, notifyStatus };
}
