#!/usr/bin/env -S npx tsx
import { writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
import { zodToJsonSchema } from "zod-to-json-schema";
import {
  ActionSchema,
  ObservationSchema,
  LocatorSchema,
  ActionVerbSchema,
  ObservationKindSchema,
  LocatorKindSchema,
} from "../packages/cu-core/src/types";

// Generate the Python validators in
// `packages/cu-core/src/python/schema.py` from the Zod schemas in
// `packages/cu-core/src/types.ts`. This keeps the two sides from drifting
// silently — the source of truth is Zod, the Python module is a build artifact
// that the epic_agent loop imports through `tools/rachael_cu/`.
//
// The generator is intentionally minimal: it dumps the literal enum values
// (verbs, locator kinds, observation kinds) and the per-verb required fields
// into a hand-written validator template. JSON Schema is also emitted
// alongside as `schema.json` so non-Python consumers can validate too.

const OUT_PY = resolve(__dirname, "../packages/cu-core/src/python/schema.py");
const OUT_JSON = resolve(__dirname, "../packages/cu-core/src/python/schema.json");

const verbs = ActionVerbSchema.options;
const obsKinds = ObservationKindSchema.options;
const locKinds = LocatorKindSchema.options;

const requiredByVerb: Record<string, string[]> = {
  Click: ["target"],
  Type: ["text"],
  Key: ["chord"],
  Hint: ["hint"],
  Scroll: [],
  Wait: [],
  Goto: ["url"],
  Shell: ["cmd"],
  Composite: ["steps"],
};

const requiredByLocator: Record<string, string[]> = {
  selector: ["css"],
  uia: [],
  hint: ["key"],
  mark: ["mark"],
  coords: ["x", "y"],
};

const py = `"""
schema.py — generated by scripts/codegen-python-schema.ts.

Do NOT edit by hand. Run \`npx tsx scripts/codegen-python-schema.ts\` after
changing the Zod schemas in packages/cu-core/src/types.ts.

Source of truth: @rachael/cu-core Action / Observation / Locator schemas.
"""

from __future__ import annotations

from typing import Any, Dict, Iterable

ACTION_VERBS = ${JSON.stringify(verbs)}
LOCATOR_KINDS = ${JSON.stringify(locKinds)}
OBSERVATION_KINDS = ${JSON.stringify(obsKinds)}

_REQUIRED_BY_VERB: Dict[str, list] = ${JSON.stringify(requiredByVerb, null, 4)}
_REQUIRED_BY_LOCATOR: Dict[str, list] = ${JSON.stringify(requiredByLocator, null, 4)}


def _require(d: Dict[str, Any], keys: Iterable[str]) -> None:
    for k in keys:
        if k not in d:
            raise ValueError(f"missing required field: {k}")


def validate_locator(loc: Dict[str, Any]) -> Dict[str, Any]:
    if not isinstance(loc, dict):
        raise ValueError("locator must be a dict")
    kind = loc.get("kind")
    if kind not in LOCATOR_KINDS:
        raise ValueError(f"unknown locator kind: {kind!r}")
    _require(loc, _REQUIRED_BY_LOCATOR.get(kind, []))
    if kind == "uia" and not any(loc.get(k) for k in ("automationId", "controlType", "name", "path")):
        raise ValueError("uia locator requires at least one of automationId/controlType/name/path")
    return loc


def validate_action(action: Dict[str, Any]) -> Dict[str, Any]:
    if not isinstance(action, dict):
        raise ValueError("action must be a dict")
    verb = action.get("verb")
    if verb not in ACTION_VERBS:
        raise ValueError(f"unknown verb: {verb!r}")
    _require(action, _REQUIRED_BY_VERB.get(verb, []))

    if verb in ("Click", "Type", "Scroll") and action.get("target") is not None:
        validate_locator(action["target"])
    if verb == "Wait" and action.get("ms") is None and action.get("until") is None:
        raise ValueError("Wait requires either ms or until")
    if verb == "Composite":
        if not isinstance(action.get("steps"), list):
            raise ValueError("Composite.steps must be a list")
        for step in action["steps"]:
            validate_action(step)
    return action


def validate_observation(obs: Dict[str, Any]) -> Dict[str, Any]:
    if not isinstance(obs, dict):
        raise ValueError("observation must be a dict")
    _require(obs, ["kind", "surfaceId", "timestamp", "digest"])
    kind = obs["kind"]
    if kind not in OBSERVATION_KINDS:
        raise ValueError(f"unknown observation kind: {kind!r}")
    if kind == "UiaTree" and not isinstance(obs.get("elements"), list):
        raise ValueError("UiaTree observation requires elements list")
    if kind in ("RawScreenshot", "SomScreenshot"):
        _require(obs, ["imageRef"])
    if kind == "TextDump":
        _require(obs, ["text"])
    return obs
`;

writeFileSync(OUT_PY, py);

const jsonSchema = {
  $schema: "http://json-schema.org/draft-07/schema#",
  title: "rachael-cu-core",
  definitions: {
    Action: zodToJsonSchema(ActionSchema, { name: "Action" }).definitions?.Action,
    Observation: zodToJsonSchema(ObservationSchema, { name: "Observation" }).definitions?.Observation,
    Locator: zodToJsonSchema(LocatorSchema, { name: "Locator" }).definitions?.Locator,
  },
};
writeFileSync(OUT_JSON, JSON.stringify(jsonSchema, null, 2));

console.log(`Wrote ${OUT_PY}`);
console.log(`Wrote ${OUT_JSON}`);
