import { db } from "../server/db";
import { programs } from "../shared/schema";
import { eq } from "drizzle-orm";

const NL = String.fromCharCode(10);

const code = [
'const NL = String.fromCharCode(10);',
'const OPENROUTER_KEY = process.env.OPENROUTER_API_KEY || "";',
'const FILTER_MODEL = "anthropic/claude-sonnet-4";',
'const SYNTH_MODEL = "anthropic/claude-sonnet-4";',
'const UA = "OrgCloud/2.0 (research-radar; +https://orgcloud.dev)";',
'',
'const SUBREDDITS = [',
'  "LocalLLaMA", "MachineLearning", "artificial", "OpenAI",',
'  "ClaudeAI", "Anthropic", "LLMDevs", "singularity",',
'  "ollama", "LangChain", "StableDiffusion", "comfyui",',
'  "SelfHosted", "OpenClaw", "agi", "ArtificialInteligence"',
'];',
'',
'function sleep(ms: number) { return new Promise(r => setTimeout(r, ms)); }',
'',
'function parseRetryAfter(val: string | null): number {',
'  if (!val) return 5000;',
'  const n = parseInt(val, 10);',
'  if (!isNaN(n)) return Math.min(n, 30) * 1000;',
'  const d = Date.parse(val);',
'  if (!isNaN(d)) return Math.min(Math.max(d - Date.now(), 1000), 30000);',
'  return 5000;',
'}',
'',
'async function retryFetch(url: string, opts: any = {}, retries = 2): Promise<Response> {',
'  opts.headers = Object.assign({ "User-Agent": UA }, opts.headers || {});',
'  opts.signal = opts.signal || AbortSignal.timeout(15000);',
'  for (let i = 0; i <= retries; i++) {',
'    try {',
'      const r = await fetch(url, opts);',
'      if (r.status === 429) {',
'        await sleep(parseRetryAfter(r.headers.get("retry-after")));',
'        continue;',
'      }',
'      if (r.ok) return r;',
'      if (i < retries) { await sleep(2000 * (i + 1)); continue; }',
'      throw new Error("HTTP " + r.status);',
'    } catch (e: any) {',
'      if (i === retries) throw e;',
'      await sleep(2000 * (i + 1));',
'    }',
'  }',
'  throw new Error("retries exhausted");',
'}',
'',
'async function callLLM(prompt: string, model: string, maxTokens = 3000): Promise<{ok: boolean; text: string}> {',
'  try {',
'    const r = await fetch("https://openrouter.ai/api/v1/chat/completions", {',
'      method: "POST",',
'      headers: { "Authorization": "Bearer " + OPENROUTER_KEY, "Content-Type": "application/json" },',
'      body: JSON.stringify({ model, messages: [{ role: "user", content: prompt }], max_tokens: maxTokens, temperature: 0.4 }),',
'      signal: AbortSignal.timeout(120000),',
'    });',
'    const d = await r.json();',
'    const text = d.choices?.[0]?.message?.content?.trim();',
'    if (text) return { ok: true, text };',
'    return { ok: false, text: "[model error: " + JSON.stringify(d.error || "no content").slice(0, 100) + "]" };',
'  } catch (e: any) { return { ok: false, text: "[model unavailable: " + (e.message || "").slice(0, 80) + "]" }; }',
'}',
'',
'async function fetchRedditRSS(sub: string): Promise<Array<{title: string; score: number; url: string; selftext: string; topComment: string; sub: string}>> {',
'  try {',
'    await sleep(500);',
'    const r = await retryFetch("https://www.reddit.com/r/" + sub + "/.rss?limit=10", {',
'      headers: { "Accept": "application/rss+xml, application/xml, text/xml" }',
'    }, 1);',
'    const xml = await r.text();',
'    const entryRe = /<entry>[\\s\\S]*?<\\/entry>/g;',
'    const results: Array<{title: string; score: number; url: string; selftext: string; topComment: string; sub: string}> = [];',
'    let entryMatch;',
'    while ((entryMatch = entryRe.exec(xml)) !== null && results.length < 8) {',
'      const entry = entryMatch[0];',
'      const titleM = entry.match(/<title[^>]*>([^<]+)<\\/title>/);',
'      const linkM = entry.match(/<link[^>]*href="([^"]+)"/);',
'      const contentM = entry.match(/<content[^>]*>([\\s\\S]*?)<\\/content>/);',
'      const title = (titleM ? titleM[1] : "").replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&#39;/g, "' + "'" + '");',
'      if (!title || title.includes("updates on")) continue;',
'      let selftext = "";',
'      if (contentM) {',
'        selftext = contentM[1].replace(/<[^>]+>/g, " ").replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&nbsp;/g, " ").replace(/\\s+/g, " ").trim().slice(0, 300);',
'      }',
'      results.push({',
'        title,',
'        score: 0,',
'        url: linkM ? linkM[1] : "",',
'        selftext,',
'        topComment: "",',
'        sub,',
'      });',
'    }',
'    return results;',
'  } catch { return []; }',
'}',
'',
'async function fetchAllReddit(): Promise<{text: string; status: string}> {',
'  const allPosts: Array<{title: string; score: number; url: string; selftext: string; topComment: string; sub: string}> = [];',
'  const failed: string[] = [];',
'  for (const sub of SUBREDDITS) {',
'    const posts = await fetchRedditRSS(sub);',
'    if (posts.length === 0) failed.push(sub);',
'    else allPosts.push(...posts);',
'  }',
'  const lines: string[] = [];',
'  for (const p of allPosts.slice(0, 50)) {',
'    let entry = "r/" + p.sub + " | " + p.title;',
'    if (p.selftext) entry += NL + "  " + p.selftext.slice(0, 200);',
'    lines.push(entry);',
'  }',
'  let status = "ok";',
'  if (failed.length > 0) {',
'    status = "partial (" + failed.length + " failed: " + failed.join(",") + ")";',
'  }',
'  return {',
'    text: "REDDIT AI/LLM (" + allPosts.length + " posts from " + (SUBREDDITS.length - failed.length) + "/" + SUBREDDITS.length + " subs via RSS):" + NL + lines.join(NL + NL),',
'    status,',
'  };',
'}',
'',
'async function fetchHN(): Promise<string> {',
'  try {',
'    const topIds = await retryFetch("https://hacker-news.firebaseio.com/v0/topstories.json").then(r => r.json());',
'    const stories: string[] = [];',
'    for (const id of topIds.slice(0, 25)) {',
'      const s = await retryFetch("https://hacker-news.firebaseio.com/v0/item/" + id + ".json").then(r => r.json());',
'      if (s && s.score >= 50) stories.push(s.title + " (" + s.score + " pts)");',
'      if (stories.length >= 12) break;',
'    }',
'    return "HN Top:" + NL + stories.join(NL);',
'  } catch { return "HN: [fetch failed]"; }',
'}',
'',
'async function fetchGitHub(): Promise<string> {',
'  const langs = ["typescript", "python", "rust"];',
'  const repos: string[] = [];',
'  for (const lang of langs) {',
'    try {',
'      const r = await retryFetch("https://github.com/trending/" + lang + "?since=daily", {',
'        headers: { "Accept": "text/html" }',
'      });',
'      const html = await r.text();',
'      const re = /class="Box-row"[\\s\\S]*?href="\\/([^"]+)"/g;',
'      let m;',
'      while ((m = re.exec(html)) !== null && repos.length < 6) {',
'        repos.push("[" + lang + "] " + m[1].replace(/\\/\\s/g, "/"));',
'      }',
'    } catch {}',
'  }',
'  return "GitHub Trending:" + NL + repos.join(NL);',
'}',
'',
'async function fetchLobsters(): Promise<string> {',
'  try {',
'    const r = await retryFetch("https://lobste.rs/hottest.json");',
'    const d = await r.json();',
'    return "Lobsters Hot:" + NL + d.slice(0, 10).filter((p: any) => p.score >= 5)',
'      .map((p: any) => p.title + " (" + p.score + " pts, " + (p.tags || []).join(",") + ")").join(NL);',
'  } catch { return "Lobsters: [fetch failed]"; }',
'}',
'',
'async function fetchLemmy(community: string): Promise<string> {',
'  try {',
'    const r = await retryFetch("https://lemmy.world/api/v3/post/list?sort=Hot&limit=10&community_name=" + community);',
'    const d = await r.json();',
'    const posts = (d.posts || []).filter((p: any) => p.counts.score >= 3).slice(0, 5)',
'      .map((p: any) => p.post.name + " (" + p.counts.score + " pts)");',
'    return "Lemmy c/" + community + ":" + NL + (posts.length ? posts.join(NL) : "[no recent hot posts]");',
'  } catch { return "Lemmy c/" + community + ": [fetch failed]"; }',
'}',
'',
'async function fetchArxiv(): Promise<string> {',
'  try {',
'    const r = await retryFetch("https://rss.arxiv.org/rss/cs.AI");',
'    const xml = await r.text();',
'    const titles: string[] = [];',
'    const re = /<item>[\\s\\S]*?<title>([^<]+)<\\/title>/g;',
'    let m;',
'    while ((m = re.exec(xml)) !== null && titles.length < 10) {',
'      const t = m[1].replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">");',
'      if (!t.includes("updates on arXiv")) titles.push(t.trim());',
'    }',
'    return "ArXiv CS.AI (recent):" + NL + titles.join(NL);',
'  } catch { return "ArXiv: [fetch failed]"; }',
'}',
'',
'async function execute() {',
'  const [redditResult, hn, gh, lobsters, lemmyML, lemmyAI, arxiv] = await Promise.all([',
'    fetchAllReddit(),',
'    fetchHN(), fetchGitHub(), fetchLobsters(),',
'    fetchLemmy("machinelearning"), fetchLemmy("artificial_intelligence"),',
'    fetchArxiv(),',
'  ]);',
'',
'  const allSources = [hn, gh, lobsters, lemmyML, lemmyAI, arxiv, redditResult.text].join(NL + NL);',
'',
'  const filterResult = await callLLM(',
'    "You are a research relevance filter for an AI engineer who builds:" + NL +',
'    "- Autonomous agent systems (planning, tool use, memory)" + NL +',
'    "- Local LLM deployment (ollama, llama.cpp, quantization)" + NL +',
'    "- Browser automation and scraping" + NL +',
'    "- Voice/speech interfaces" + NL +',
'    "- Knowledge management and org-mode-style tools" + NL +',
'    "- OpenClaw (AI governance, proposals, voting)" + NL + NL +',
'    "From this raw feed, select ONLY the 15-20 most relevant items. For each, preserve the source, title, score, and top comment if available. Drop anything generic, off-topic, political hot takes, memes, or low-signal." + NL + NL +',
'    "RAW FEED:" + NL + allSources + NL + NL +',
'    "Output ONLY the filtered items, one per line, preserving original formatting. No commentary.",',
'    FILTER_MODEL, 3000',
'  );',
'',
'  const synthInput = filterResult.ok ? filterResult.text : allSources.slice(0, 6000);',
'',
'  const briefingResult = await callLLM(',
'    "You are a senior research analyst for an AI/LLM-focused developer. Synthesize these curated items into an actionable briefing:" + NL + NL +',
'    synthInput + NL + NL +',
'    "Produce these sections:" + NL +',
'    "1. WHAT' + "'" + 'S NEW: Top 5 developments worth knowing (include why each matters)" + NL +',
'    "2. COMMUNITY PULSE: What the Reddit AI community is excited/worried about (cite specific subs and top comments)" + NL +',
'    "3. EXPERIMENTS: 3 concrete things to try this week with links or repo names" + NL +',
'    "4. LOCAL LLM WATCH: Any new models, quantizations, or deployment techniques" + NL +',
'    "5. LLM EXPLOITATION: Notable jailbreaks, prompt injection, security concerns" + NL +',
'    "6. SYSTEM PROPOSALS: 2 improvements for an automated agent/research system" + NL + NL +',
'    "Be concise, specific, and actionable. Include Reddit community sentiment where relevant.",',
'    SYNTH_MODEL, 4000',
'  );',
'',
'  const briefing = briefingResult.text;',
'  const redditCount = (redditResult.text.match(/r\\//g) || []).length;',
'  const hnCount = (hn.match(/pts\\)/g) || []).length;',
'  const arxivCount = (arxiv.split(NL).length - 1);',
'  const ghCount = (gh.split(NL).length - 1);',
'  const statusLine = "reddit:" + redditCount + "(" + redditResult.status + ") hn:" + hnCount + " arxiv:" + arxivCount + " gh:" + ghCount;',
'  const llmStatus = (filterResult.ok ? "filter:ok" : "filter:FAIL") + " " + (briefingResult.ok ? "synth:ok" : "synth:FAIL");',
'  const metricStr = statusLine + " | " + llmStatus;',
'',
'  const proposals: Array<{section: string; diff: string; reason: string}> = [];',
'  const re = /\\d+\\.\\s*([^:]+):\\s*([\\s\\S]*?)(?=\\d+\\.|$)/g;',
'  let m;',
'  while ((m = re.exec(briefing)) !== null) {',
'    proposals.push({ section: m[1].trim(), diff: "", reason: m[2].trim().slice(0, 500) });',
'  }',
'',
'  return { summary: briefing + NL + NL + "--- Sources: " + metricStr, metric: metricStr, proposals };',
'}',
].join(NL);

async function main() {
  const existing = await db.select().from(programs).where(eq(programs.name, "research-radar"));
  if (existing.length === 0) {
    console.log("research-radar not found");
    process.exit(1);
  }

  await db.update(programs).set({ code }).where(eq(programs.id, existing[0].id));
  console.log("Updated research-radar code, length=" + code.length);
  process.exit(0);
}

main().catch(e => { console.error(e); process.exit(1); });
